server:
  port: 38888

management:
  endpoint:
    health:
      show-details: when-authorized

sensoric:
  security:
    user:
      name: configuration-user
      roles: USER
    manager:
      name: configuration-manager
      roles: ACTUATOR
---
spring:
  profiles: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kamiKAZIK/sensoric-settings.git

sensoric:
  security:
    user:
      password: '{noop}configuration-user'
    manager:
      password: '{noop}configuration-manager'
